name: PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - dev

jobs:
  validate-title:
    name: Validate PR Title
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit PR Title Check
        uses: ytanikin/pr-conventional-commits@v1
        with:
          task_types: '["feat","fix","docs","style","refactor","perf","test","chore","revert","ci"]'
          add_label: 'false'

  validate-docker-build:
    name: Verify Frontend Dockerfile Build
    # This job needs the title to be valid first
    needs: validate-title
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Dockerfile can be built
        uses: docker/build-push-action@v5
        with:
          # We explicitly set the context to the frontend directory
          context: ./frontend
          # The file path is now relative to that context
          file: ./frontend/Dockerfile
          push: false # This is a dry-run
          tags: local/test-build-frontend:latest
          # Provided dummy values for the frontend build
          build-args: |
            VITE_CLERK_PUBLISHABLE_KEY=pk_test_dummykeyforpr12345
            VITE_BACKEND1_BASE_URL=http://localhost:3000
            VITE_BACKEND2_BASE_URL=http://localhost:3001
